palladiumkenya/kenyaemrMigration

IQCare_ValidatedQueries.sql
=> Migration validation queries

IQCare_ValidatedQueries.sql
These are the validated migration queries from IQCare. KenyaEMR dev to update his DLL
=> CCC enrollment progress

transformations/Migrate_demographics.ktr, transformations/Migrate_enhanced_adherence.ktr, transformations/Transform_demographics.ktr, transformations/Transform_hiv_regimen_history.ktr, transformations/Transform_vital_labs.ktr
=> Updated nehanced_adherenc pill count, demographics gender,labs without test results

transformations/Migrate_hiv_followup.ktr, transformations/Migrate_ipt_program.ktr, transformations/Migrate_regimen_history.ktr, transformations/Migration_Job_1.kjb, transformations/Transform_hiv_regimen_history.ktr, transformations/Transform_hts_initial.ktr, transformations/Transform_hts_retest.ktr, transformations/Validations/Validate_anc_number.ktr, transformations/Validations/Validate_mch_anc_visit.ktr, transformations/Validations/Validate_mch_enrollment.ktr
Added validations for hiv_enrollment_TI_facility, mch anc_number,added IPT program and regimens_history updated by ken
=> Added validations for hiv_enrollment_TI_facility, mch anc_number,added IPT program and regimens_history updated by ken

transformations/Migrate_hts_tracing.ktr, transformations/Migrate_regimen_history.ktr, transformations/Migration_Job_1.kjb, transformations/Test/ART_Regimen_Order.ktr, transformations/Validations/ART_Regimen_Order.ktr
Added hts_tracing updates and reverted earlier regimens history from Wambua
=> Added hts_tracing updates and reverted earlier regimens history 

transformations/Migrate_hiv_followup.ktr, transformations/Migrate_regimen_history.ktr, transformations/Migration_Job_1.kjb
=> Updated HIV-Followup on missing bluecard TCAs and reverted Wambuas RH extraction

transformations/Migrate_hts_test.ktr
Updated Migrate_hts_test added Gichukis bug fix
=> Updated Migrate_hts_test added Gichukis bug fix

transformations/Migrate_hts_test.ktr, transformations/Migrate_tb_screening.ktr
Added NULL Encounter_ID to migrate_hts_test, updated tb_screening
=> Added NULL Encounter_ID to migrate_hts_test, updated tb_screening

transformations/Migrate_hiv_enrollments.ktr, transformations/Transform_hts_initial.ktr, transformations/Transform_hts_retest.ktr
Updated HIV_Enrollment_v3.0 and PNS concept entrypoint in HTS"
=> Updated HIV_Enrollment_v3.0 and PNS concept entrypoint in HTS

.gitignore, transformations/Migrate_hei_followup.ktr, transformations/Transform_hts_initial.ktr, transformations/Transform_hts_retest.ktr
Updated mapping for HP: Health Facility Patients concept to 164163 for HTS Strategy
=> Updated mapping for HP: Health Facility Patients concept to 164163 for HTS Strategy

transformations/Migrate_hiv_enrollments.ktr
Updated HIV_enrollments - Added date_confirmed_hiv_positive form blue card records IQCare
=> Updated HIV_enrollments - Added date_confirmed_hiv_positive form blue card records IQCare

transformations/Transform_art_fastrack.ktr, transformations/Transform_hiv_followup.ktr, transformations/Transform_vital_labs.ktr
Updated CTX_dispensed for no answer in hiv_followup,added lab_test grouping in vital labs
=> Updated CTX_dispensed for no answer in hiv_followup,added lab_test grouping in vital labs

transformations/Migrate_art_fastrack.ktr, transformations/Migrate_otz_enrollment.ktr, transformations/Migrate_otz_outcome.ktr, transformations/Migration_Job_1.kjb, transformations/Transform_differentiated_care.ktr, transformations/Transform_hei_patient_program.ktr, transformations/Transform_mch_patient_program.ktr, transformations/Transform_otz_activity.ktr, transformations/Transform_otz_enrollment.ktr, transformations/Transform_otz_outcome.ktr, transformations/Transform_otz_patient_program.ktr, transformations/Transform_ovc_patient_program.ktr, transformations/Transform_vital_labs.ktr
Added OTZ,HEI,MCH.OVC programs, Added obsgroup in general_examinations
=> Added OTZ,HEI,MCH.OVC programs, Added obsgroup in general_examinations

transformations/Migrate_disability_type.ktr, transformations/Transform_disability_types.ktr
Updated disability_type dataset: removed duplicated fields
=> Updated disability_type dataset: removed duplicated fields

transformations/Migration_Job_1.kjb, transformations/Transform_hei_outcome.ktr, transformations/Transform_hei_patient_program.ktr, transformations/Transform_hiv_program_discontinuations.ktr, transformations/Transform_ipt_outcome.ktr, transformations/Transform_mch_program_discontinuations.ktr, transformations/Transform_ovc_outcome.ktr, transformations/Transform_ovc_patient_program.ktr
Updated HIV program discontinuation: Made encounter_date equal to completion_date"
=> Updated HIV program discontinuation: Made encounter_date equal to completion_date

transformations/Migration_Job_1.kjb
Updated demographics_tr added phone number validator
=> Updated demographics_tr added phone number validator

transformations/Validations/Validate_demographics.ktr
Updated demographics_tr added next_of_kin phone number validator
=> Updated demographics_tr added next_of_kin phone number validator

DML_4_Datasets/DML_HIV Follow up - Combined_v9.0.sql, transformations/Migrate_hiv_enrollments.ktr, transformations/Migrate_hiv_followup.ktr, transformations/Transform_otz_outcome.ktr
Updated audit data created_by and create_date for hiv_enrollment
=> Updated audit data created_by and create_date for hiv_enrollment

transformations/Migrate_labs.ktr, transformations/Test/ART_Regimen_Order.ktr, transformations/Transform_ipt_outcome.ktr, transformations/Transform_otz_outcome.ktr
Updated migrate_labs to use created_by and ordered_by for Audit
=> Updated migrate_labs to use created_by and ordered_by for Audit

DML_4_Datasets/DML_Patient_DemographicsForOnlyPatients_v4.0.sql, DML_4_Datasets/DML_Patient_Demographics_V4.0.sql, transformations/Migrate_demographics.ktr
Updated demographics - DOB sourced from mst_patient,Person and Pateint tables
=> Updated demographics - DOB sourced from mst_patient,Person and Pateint tables
